markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Adithya Venkatesh
url: bloomark.github.io
description: I summarize here.
twitter: bloomark
